### ISSUE TITLE
Determine dates that UW-UH Station was down

### ISSUE THREAD

**Issue by m-ball3** [uw-echospace/batmo#3]
These dates will need to be supplemented with UW-A station data. 

Wu-Jung asked: "do these stations track each other?" 
- find out what that means and if they do or not.

**Comment by leewujung** [comment]
> do these stations track each other?

I was wondering given the locations of these stations, if you plot the data together, say temperature vs time curves, would data from the two stations fall on top of each other, or generally follow the same trend but have some differences, or if they are different, how much?

**Comment by m-ball3** [comment]
Thank you so much for the clarification- I will work on finding that out this week! (:

**Comment by m-ball3** [comment]
2022 dates UW UH Station was down: 
x-6/09 , 6/14-8/23 , 8/28-10/4 
x indicates indefinite date the station was down as the sample was run from 6/01 - 10/31. data is unavailable from 6/01-6/09, but also possibly before 6/01. 
from 10/5 to the end of the sample (10/31), data is available.
Unfortunately, this means that UW UH data is basically unusable for 2022. UWA station will have to be used. 

As far as I can tell from the limited 2022 UW UH data, the UWA station pretty consistently reports temperatures ~6 degrees F cooler than the UW UH station does. 

I still need to look into this year. It may make more sense to use UWA's data instead. Bring this up in Thursday meeting?
